### ISSUE TITLE
Example is not working.

### ISSUE THREAD

**Issue by Koepel** [Palatis/arduino-softpwm#4]
Thank you for the arduino-softpwm library, I like the way it works.

I use it for an ATmega8 by adding "#define TIMSK1 TIMSK".

The example was confusing for me, because the external definition "SOFTPWM_DEFINE_EXTERN_OBJECT_WITH_PWM_LEVELS" is also defined, but not needed for the example.

The example in the loop() is not working. My setup() takes about 10 seconds, therefor micros() has a high value when entering the loop(). The for-loop with 'i' stays at '0' and never gets to the next one. A value is added to micros() with "micros() + WAIT", that introduces the rollover problem. Could you rewrite the example and make it much simpler ? For example a ramp up for each output one by one with normal delays.

For motors it might be useful to have an example that uses an increasing frequency to find the frequency that is the least audible.

**Comment by Palatis** [comment]
no, I intentionally *NOT* using `delay()` to show the async nature of the
lib.
if there is a rollover prob, use `micros() - last > WAIT`, that should take
care of the roll-over.

**Comment by Palatis** [comment]
also, try setting `next = micros() + WAIT` by the end of `setup()` may help.

**Comment by Koepel** [comment]
I'm using my own sequence and ramps now, and I'm not going to use micros() like that. Sorry. The goal is to show how the library can be used. I don't see any harm in using delay() for a simple example. Your while-loops are also used as a fixed delay and could be replaced by delayMicroseconds(). 
The correct way to use millis() and micros() is:
`if( micros() - previousMicros > interval)`
The substraction with unsigned long prevents any rollover problem.

I have a few motors, and I can run them with a PWM of 1000Hz on a  8MHz ATmega8 with 30 PWM levels. That's great!

One more thing: The library is for 8-bit AVR chips, and they don't have 'double' floating point. The compiler translates that into single precision 'float'.

**Comment by Palatis** [comment]
avoiding `delay()` is intended.

but the example should be reworked, anyway.
just i dont have free time to work on this, I'll accept PR :-)
